version: '3'
    
services:
  webApp.MVC:
    container_name: SmartRdo.MVC
    image: smart-rdo-mvc
    build:
      context: .
      dockerfile: src/SmartRdo.MVC/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "0.0.0.0:5055:80"
    networks:
      - dockersql-network
    depends_on:
      - db.database
      
  webApp.API:
    container_name: SmartRdo.API
    image: smart-rdo-api
    build:
      context: .
      dockerfile: src/SmartRdo.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "0.0.0.0:5000:5000"
    networks:
      - dockersql-network
    depends_on:
      - db.database

  db.database:
    container_name: smart_rdo_db
    image: postgres
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - dockersql-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=SmartRDO
    volumes:
      - /home/docker/pgdata:/var/lib/postgresql/data
     
networks: 
  dockersql-network:
    driver: bridge    