version: '3'
    
services:
  db.database:
    image: postgres
    container_name: smart_rdo_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=SmartRDO
    volumes:
      - /home/docker/pgdata:/var/lib/postgresql/data
      
    