version: '3'
    
services:
  db.database:
    image: postgres
    container_name: postgres_smart_rdo
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=SmartRDO   
    